[tool.ruff]
line-length = 120
ignore = ["E402", "F403"]

[tool.ruff.lint]
per-file-ignores = { "alembic/env.py" = ["E402", "F403"] }

[tool.isort]
profile = "black"
known_first_party = ["lib", "users", "llm"]
src_paths = ["lib", "users", "llm"]

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true

